# Generated by Django 2.2 on 2019-08-28 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('celular', models.CharField(error_messages={'celular_validar_length': 'El numero de celular debe tener de 10 a 15 dígitos.', 'unique': 'El numero de celular ya está registrado.'}, help_text='De 10 a 15 números', max_length=15, unique=True, verbose_name='Celular')),
                ('cedula', models.CharField(error_messages={'cedula_validar_length': 'La cédula debe contener 10 dígitos.', 'unique': 'El numero de cédula ya está registrado.'}, help_text='10 números', max_length=10, unique=True, verbose_name='Cédula')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
