# Generated by Django 2.2 on 2019-08-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(error_messages={'cedula_validar_length': 'La cédula debe contener 10 dígitos.', 'unique': 'El numero de cédula ya está registrado.'}, max_length=10, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(error_messages={'celular_validar_length': 'El numero de celular debe tener de 10 a 15 dígitos.', 'unique': 'El numero de celular ya está registrado.'}, max_length=15, unique=True, verbose_name='Celular'),
        ),
    ]
