# Generated by Django 2.2 on 2019-07-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0003_auto_20190705_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(error_messages={'unique': 'El numero de cédula ya está registrado.'}, max_length=10, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='celular',
            field=models.CharField(error_messages={'unique': 'El numero de celular ya está registrado.'}, max_length=15, unique=True, verbose_name='Celular'),
        ),
    ]
