# Generated by Django 2.2 on 2019-08-28 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnunciadoEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField(max_length=500, verbose_name='Enunciado')),
                ('tipo_respuesta', models.IntegerField(choices=[(0, 'Respuesta única'), (1, 'Opción múltiple'), (2, 'Respuesta única (con imagen)'), (3, 'Opción múltiple (con imagen)')], verbose_name='Tipo de Respuesta')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_enunciado/', verbose_name='Imagen para el enunciado (Opcional)')),
            ],
            options={
                'verbose_name': 'Enunciado',
                'verbose_name_plural': 'Enunciados',
            },
        ),
        migrations.CreateModel(
            name='OpcionEnunciado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.TextField(blank=True, max_length=200, null=True, verbose_name='Enunciado')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fotos_opciones_enunciado/', verbose_name='Imagen')),
                ('enunciado_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.EnunciadoEvaluacion', verbose_name='Enunciado Evaluacion')),
            ],
            options={
                'verbose_name': 'Opción del Enunciado',
                'verbose_name_plural': 'Opciones del Enunciado',
            },
        ),
        migrations.CreateModel(
            name='SeleccionMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.BooleanField(verbose_name='Respuesta')),
                ('opcion_enunciado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.OpcionEnunciado')),
            ],
            options={
                'verbose_name': 'Seleccion Multiple',
            },
        ),
        migrations.CreateModel(
            name='RelacionarConcepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_enunciado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.OpcionEnunciado')),
                ('respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_respuesta', to='evaluacion.OpcionEnunciado')),
            ],
            options={
                'verbose_name': 'Relacionar Concepto',
                'verbose_name_plural': 'Relacionar Conceptos',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_maxima', models.FloatField(default=100)),
                ('calificacion_minima', models.FloatField(default=70)),
                ('modulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curso.Modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='EstudianteEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.EstudianteCurso')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.Evaluacion')),
            ],
            options={
                'verbose_name': 'Evaluación del Estudiante',
                'verbose_name_plural': 'Evaluaciones de los Estudiantes',
            },
        ),
        migrations.AddField(
            model_name='enunciadoevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.Evaluacion', verbose_name='Evaluación'),
        ),
        migrations.AddField(
            model_name='enunciadoevaluacion',
            name='submodulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.SubModulo', verbose_name='SubModulo'),
        ),
        migrations.CreateModel(
            name='DetalleEstudianteEvaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion_obtenida', models.FloatField()),
                ('calificacion_maxima', models.FloatField()),
                ('enunciado_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.EnunciadoEvaluacion')),
                ('estudiante_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.EstudianteEvaluacion')),
            ],
            options={
                'verbose_name': 'Detalle de la evaluación',
                'verbose_name_plural': 'Detalle de Evaluaciones',
            },
        ),
        migrations.CreateModel(
            name='CalificacionSeleccionMultiple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.EstudianteEvaluacion', verbose_name='Estudiante')),
                ('respuesta_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_respuesta_estudiante', to='evaluacion.SeleccionMultiple', verbose_name='Respuesta del estudiante')),
                ('seleccion_multiple', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.SeleccionMultiple', verbose_name='Respuesta correcta')),
            ],
            options={
                'verbose_name': 'Calificacion de Seleccion Multiple',
            },
        ),
        migrations.CreateModel(
            name='CalificacionRelacionarConcepto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.EstudianteEvaluacion', verbose_name='Estudiante')),
                ('relacionar_concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.RelacionarConcepto', verbose_name='Pregunta')),
                ('respuesta_estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.OpcionEnunciado', verbose_name='Respuesta del Estudiante')),
            ],
            options={
                'verbose_name': 'Calificacion Relacionar Concepto',
            },
        ),
    ]
