# Generated by Django 2.2 on 2019-07-05 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleestudianteevaluacion',
            options={'verbose_name': 'Detalle de la evaluación', 'verbose_name_plural': 'Detalle de Evaluaciones'},
        ),
    ]
