# Generated by Django 2.2 on 2019-07-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleestudianteevaluacion',
            name='calificacion_maxima',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detalleestudianteevaluacion',
            name='calificacion_obtenida',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='estudianteevaluacion',
            name='calificacion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='calificacion_maxima',
            field=models.FloatField(default=100),
        ),
    ]
