# Generated by Django 2.2 on 2019-07-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0002_auto_20190722_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Modulo', verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='tiporespuesta',
            name='descripcion',
            field=models.IntegerField(choices=[(0, 'Respuesta única'), (1, 'Opción múltiple'), (2, 'Relacionar concepto')], verbose_name='Descripción'),
        ),
    ]
