# Generated by Django 2.2 on 2019-07-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0003_auto_20190722_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enunciadoevaluacion',
            name='tipo_respuesta',
            field=models.IntegerField(choices=[(0, 'Respuesta única'), (1, 'Opción múltiple'), (2, 'Relacionar concepto')], verbose_name='Tipo de Respuesta'),
        ),
        migrations.DeleteModel(
            name='TipoRespuesta',
        ),
    ]
