# Generated by Django 2.2 on 2019-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0004_auto_20190722_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enunciadoevaluacion',
            name='foto',
            field=models.ImageField(upload_to='fotos_enunciado/', verbose_name='Imagen para el enunciado (No es Obligatorio)'),
        ),
    ]
