# Generated by Django 2.2 on 2019-07-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0006_auto_20190722_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enunciadoevaluacion',
            name='submodulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.SubModulo', verbose_name='SubModulo'),
        ),
    ]
