# Generated by Django 2.2 on 2019-08-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0010_auto_20190724_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacion',
            name='calificacion_minima',
            field=models.FloatField(default=70),
        ),
    ]
