# Generated by Django 2.2 on 2019-08-06 01:19

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0011_evaluacion_calificacion_minima'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcionenunciado',
            name='imagen',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=50, null=True, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='enunciadoevaluacion',
            name='enunciado',
            field=models.TextField(max_length=500, verbose_name='Enunciado'),
        ),
        migrations.AlterField(
            model_name='opcionenunciado',
            name='opcion',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Enunciado'),
        ),
    ]
