# Generated by Django 2.2 on 2019-08-06 01:28

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0012_auto_20190805_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcionenunciado',
            name='imagen',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=500, null=True, verbose_name='Imagen'),
        ),
    ]
