# Generated by Django 2.2 on 2019-08-06 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0014_auto_20190805_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='modulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='curso.Modulo', verbose_name='Módulo'),
        ),
    ]
