# Generated by Django 2.2 on 2019-08-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0015_auto_20190805_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enunciadoevaluacion',
            name='tipo_respuesta',
            field=models.IntegerField(choices=[(0, 'Respuesta única'), (1, 'Opción múltiple'), (2, 'Respuesta única (con imagen)'), (3, 'Opción múltiple (con imagen)')], verbose_name='Tipo de Respuesta'),
        ),
    ]
