# Generated by Django 2.2 on 2019-08-15 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0016_auto_20190806_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enunciadoevaluacion',
            name='evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.Evaluacion', verbose_name='Evaluación'),
        ),
        migrations.AlterField(
            model_name='enunciadoevaluacion',
            name='submodulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curso.SubModulo', verbose_name='SubModulo'),
        ),
        migrations.AlterField(
            model_name='opcionenunciado',
            name='enunciado_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.EnunciadoEvaluacion', verbose_name='Enunciado Evaluacion'),
        ),
    ]
