# Generated by Django 2.2 on 2019-08-24 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0018_auto_20190824_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacionarconcepto',
            name='opcion_enunciado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.OpcionEnunciado'),
        ),
        migrations.AlterField(
            model_name='seleccionmultiple',
            name='opcion_enunciado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaluacion.OpcionEnunciado'),
        ),
    ]
