# Generated by Django 2.2 on 2019-08-26 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0019_auto_20190824_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calificacionrelacionarconcepto',
            name='estudiante',
        ),
        migrations.RemoveField(
            model_name='calificacionseleccionmultiple',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='calificacionrelacionarconcepto',
            name='estudiante_evaluacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='evaluacion.EstudianteEvaluacion', verbose_name='Estudiante'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='calificacionseleccionmultiple',
            name='estudiante_evaluacion',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='evaluacion.EstudianteEvaluacion', verbose_name='Estudiante'),
            preserve_default=False,
        ),
    ]
