# Generated by Django 2.2 on 2019-08-27 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0020_auto_20190825_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionseleccionmultiple',
            name='respuesta_estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_respuesta_estudiante', to='evaluacion.SeleccionMultiple', verbose_name='Respuesta del estudiante'),
        ),
        migrations.AlterField(
            model_name='calificacionseleccionmultiple',
            name='seleccion_multiple',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='evaluacion.SeleccionMultiple', verbose_name='Respuesta correcta'),
        ),
    ]
