# Generated by Django 2.2 on 2019-07-15 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_audio', models.CharField(max_length=100, verbose_name='Nombre del audio')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audios/', verbose_name='Audio')),
            ],
            options={
                'verbose_name': 'Audio',
                'verbose_name_plural': 'Audios',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Curso')),
                ('descripcion', models.TextField(max_length=600, verbose_name='Descripción')),
                ('comentario', models.TextField(max_length=600, verbose_name='Comentario')),
                ('icono', models.ImageField(blank=True, null=True, upload_to='fotos_curso/', verbose_name='Icono')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_foto', models.CharField(max_length=100, verbose_name='Nombre de la foto')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos/', verbose_name='Foto')),
            ],
            options={
                'verbose_name': 'Foto',
                'verbose_name_plural': 'Fotos',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=600, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Item para Recurso',
                'verbose_name_plural': 'Items para Recursos',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Numero del Módulo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=600, verbose_name='Descripcion')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
            },
        ),
        migrations.CreateModel(
            name='SubModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='AnteMódulo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('texto', models.TextField(blank=True, max_length=10000, verbose_name='Contenido')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Modulo', verbose_name='Módulo')),
            ],
            options={
                'verbose_name': 'AnteMódulo',
                'verbose_name_plural': 'AnteMódulos',
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_video', models.CharField(max_length=100, verbose_name='Nombre del vídeo')),
                ('link_video', models.TextField(max_length=500, verbose_name='Link el vídeo')),
            ],
            options={
                'verbose_name': 'Vídeo',
                'verbose_name_plural': 'Vídeos',
            },
        ),
        migrations.CreateModel(
            name='VideoSubModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.SubModulo')),
                ('video', models.ManyToManyField(to='curso.Video')),
            ],
            options={
                'verbose_name': 'Vídeo para SubModulo',
                'verbose_name_plural': 'Vídeos para SubModulos',
            },
        ),
        migrations.CreateModel(
            name='RecursoItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(max_length=600, verbose_name='Descripción')),
                ('item', models.ManyToManyField(to='curso.Item', verbose_name='Item')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Recurso', verbose_name='Recurso')),
            ],
            options={
                'verbose_name': 'Item de Recurso',
                'verbose_name_plural': 'Items de Recursos',
            },
        ),
        migrations.CreateModel(
            name='FotoSubModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ManyToManyField(to='curso.Foto')),
                ('sub_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.SubModulo')),
            ],
            options={
                'verbose_name': 'Foto de SubModulo',
                'verbose_name_plural': 'Fotos de SubModulos',
            },
        ),
        migrations.CreateModel(
            name='EstudianteCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cursos', models.ManyToManyField(to='curso.Curso', verbose_name='Cursos')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.Estudiante', verbose_name='Elija al Estudiante')),
            ],
            options={
                'verbose_name': 'Estudiante del Curso',
                'verbose_name_plural': 'Estudiantes del Curso',
            },
        ),
        migrations.CreateModel(
            name='AudioSubModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.ManyToManyField(to='curso.Audio')),
                ('sub_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.SubModulo')),
            ],
            options={
                'verbose_name': 'Audio para SubModulo',
                'verbose_name_plural': 'Audios para SubModulos',
            },
        ),
    ]
