# Generated by Django 2.2 on 2019-07-22 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantecurso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.Estudiante', unique=True, verbose_name='Elija al Estudiante'),
        ),
        migrations.AlterField(
            model_name='submodulo',
            name='titulo',
            field=models.CharField(max_length=200, unique=True, verbose_name='Título'),
        ),
    ]
