# Generated by Django 2.2 on 2019-07-22 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20190722_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantecurso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.Estudiante', verbose_name='Elija al Estudiante'),
        ),
    ]
