# Generated by Django 2.2 on 2019-07-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20190705_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antemodulo',
            name='numero',
            field=models.IntegerField(verbose_name='AnteMódulo'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='numero',
            field=models.IntegerField(verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='submodulo',
            name='numero',
            field=models.IntegerField(verbose_name='SubMódulo'),
        ),
    ]
