# Generated by Django 2.2 on 2019-08-04 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiante', '0001_initial'),
        ('curso', '0003_auto_20190722_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudianteSubModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='estudiante.Estudiante', verbose_name='Estudiante Del Curso')),
                ('submodulos', models.ManyToManyField(to='curso.SubModulo', verbose_name='SubModulos cursados')),
            ],
        ),
    ]
