# Generated by Django 2.2 on 2019-07-05 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20190705_1126'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antemodulo',
            options={'ordering': ('numero',), 'verbose_name': 'AnteMódulo', 'verbose_name_plural': 'AnteMódulos'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ('numero',), 'verbose_name': 'Módulo', 'verbose_name_plural': 'Módulos'},
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.CharField(max_length=350, verbose_name='Link del vídeo en YouTube'),
        ),
    ]
