# Generated by Django 2.2 on 2019-08-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_estudiantesubmodulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantesubmodulo',
            name='submodulos',
            field=models.ManyToManyField(blank=True, null=True, to='curso.SubModulo', verbose_name='SubModulos cursados'),
        ),
    ]
