# Generated by Django 2.2 on 2019-07-07 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_auto_20190705_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.TextField(max_length=600, verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='comentario',
            field=models.TextField(max_length=600, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(max_length=600, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Curso'),
        ),
        migrations.AlterField(
            model_name='estudiantecurso',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiante.Estudiante', verbose_name='Elija al Estudiante'),
        ),
        migrations.AlterField(
            model_name='foto',
            name='foto',
            field=models.TextField(max_length=600, verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='item',
            name='descripcion',
            field=models.TextField(max_length=600, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='descripcion',
            field=models.TextField(max_length=600, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='recursoitem',
            name='descripcion',
            field=models.TextField(max_length=600, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.TextField(max_length=600, verbose_name='Link del vídeo en YouTube'),
        ),
    ]
