# Generated by Django 2.2 on 2019-07-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_auto_20190707_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='icono',
            field=models.TextField(blank=True, max_length=600, null=True, verbose_name='Icono'),
        ),
    ]
