# Generated by Django 2.2 on 2019-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_curso_icono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='numero',
            field=models.IntegerField(verbose_name='Numero del Módulo'),
        ),
    ]
