# Generated by Django 2.2 on 2019-08-11 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0006_auto_20190805_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantecurso',
            name='estudiante',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='estudiante.Estudiante', verbose_name='Elija al Estudiante'),
        ),
    ]
