# Generated by Django 2.2 on 2019-07-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_auto_20190708_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antemodulo',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
