# Generated by Django 2.2 on 2019-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0008_auto_20190708_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursoitem',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='submodulo',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
